{
    "docs": "https://docs.ansible.com/ansible-core/2.15/dev_guide/testing/sanity/pylint.html", 
    "results": [
        {
            "message": "The test `ansible-test sanity --test pylint` [[explain](https://docs.ansible.com/ansible-core/2.15/dev_guide/testing/sanity/pylint.html)] failed with 1 error:", 
            "output": "plugins/modules/ovh/dns/ovh_dns_record.py:84:0: misplaced-future: __future__ import is not the first non docstring statement"
        }
    ], 
    "verified": false
}
